export const categoryData = [
  {
    name: 'Content Safety & Toxicity',
    description: 'Tests for harmful, toxic, or inappropriate content generation',
    category: 'Content_Safety_Toxicity',
    probes: [
      'lmrc.Bullying',
      'lmrc.Deadnaming',
      'lmrc.Profanity',
      'lmrc.QuackMedicine',
      'lmrc.SexualContent',
      'lmrc.Sexualisation',
      'lmrc.SlurUsage',
      'realtoxicityprompts.RTPBlank',
      'continuation.ContinueSlursReclaimedSlurs',
    ],
  },
  {
    name: 'Data Leakage & Privacy',
    description: 'Tests for data leakage and privacy violations',
    category: 'Data_Leakage_Privacy',
    probes: [
      'leakreplay.GuardianCloze',
      'leakreplay.GuardianComplete',
      'leakreplay.LiteratureCloze',
      'leakreplay.LiteratureComplete',
      'leakreplay.NYTCloze',
      'leakreplay.PotterCloze',
      'xss.ColabAIDataLeakage',
      'xss.MarkdownImageExfil',
    ],
  },
  {
    name: 'Encoding & Obfuscation',
    description: 'Tests for encoded and obfuscated attack vectors',
    category: 'Encoding_Obfuscation',
    probes: [
      'encoding.InjectAscii85',
      'encoding.InjectBase16',
      'encoding.InjectBase32',
      'encoding.InjectBase64',
      'encoding.InjectHex',
      'encoding.InjectMorse',
      'encoding.InjectROT13',
      'encoding.InjectZalgo',
      'ansiescape.AnsiEscaped',
      'ansiescape.AnsiRaw',
    ],
  },
  {
    name: 'Full Scan',
    description: 'Comprehensive security testing across all categories - WARNING: This will take significant time to complete and may require substantial computational resources',
    category: 'Full_Scan',
    probes: [
      'lmrc.Bullying',
      'lmrc.Deadnaming',
      'lmrc.Profanity',
      'lmrc.QuackMedicine',
      'lmrc.SexualContent',
      'lmrc.Sexualisation',
      'lmrc.SlurUsage',
      'realtoxicityprompts.RTPBlank',
      'continuation.ContinueSlursReclaimedSlurs',
      'dan.Ablation_Dan_11_0',
      'dan.AutoDANCached',
      'dan.DanInTheWild',
      'goodside.Tag',
      'goodside.ThreatenJSON',
      'goodside.WhoIsRiley',
      'promptinject.HijackHateHumans',
      'promptinject.HijackKillHumans',
      'promptinject.HijackLongPrompt',
      'latentinjection.LatentInjectionFactSnippetEiffel',
      'latentinjection.LatentInjectionReport',
      'latentinjection.LatentInjectionResume',
      'latentinjection.LatentJailbreak',
      'encoding.InjectAscii85',
      'encoding.InjectBase16',
      'encoding.InjectBase32',
      'encoding.InjectBase64',
      'encoding.InjectHex',
      'encoding.InjectMorse',
      'encoding.InjectROT13',
      'encoding.InjectZalgo',
      'ansiescape.AnsiEscaped',
      'ansiescape.AnsiRaw',
      'leakreplay.GuardianCloze',
      'leakreplay.GuardianComplete',
      'leakreplay.LiteratureCloze',
      'leakreplay.LiteratureComplete',
      'leakreplay.NYTCloze',
      'leakreplay.PotterCloze',
      'xss.ColabAIDataLeakage',
      'xss.MarkdownImageExfil',
      'malwaregen.Evasion',
      'malwaregen.Payload',
      'malwaregen.SubFunctions',
      'malwaregen.TopLevel',
      'exploitation.JinjaTemplatePythonInjection',
      'exploitation.SQLInjectionEcho',
      'grandma.Substances',
      'grandma.Win10',
      'grandma.Win11',
      'packagehallucination.JavaScript',
      'packagehallucination.Python',
      'packagehallucination.Ruby',
      'packagehallucination.Rust',
      'atkgen.Tox',
      'misleading.FalseAssertion',
      'donotanswer.MisinformationHarms',
      'phrasing.FutureTense',
      'phrasing.PastTense',
      'divergence.Repeat',
      'snowball.GraphConnectivity',
      'suffix.GCGCached',
      'tap.TAPCached',
      'topic.WordnetControversial',
      'grandma.Slurs',
    ],
  },
  {
    name: 'Jailbreaking & DAN Attacks',
    description: 'Tests for jailbreak attempts and Do Anything Now (DAN) style attacks',
    category: 'Jailbreaking_DAN_Attacks',
    probes: [
      'dan.Ablation_Dan_11_0',
      'dan.AutoDANCached',
      'dan.DanInTheWild',
      'goodside.Tag',
      'goodside.ThreatenJSON',
      'goodside.WhoIsRiley',
    ],
  },
  {
    name: 'Malware & Exploitation',
    description: 'Tests for malware generation and system exploitation',
    category: 'Malware_Exploitation',
    probes: [
      'malwaregen.Evasion',
      'malwaregen.Payload',
      'malwaregen.SubFunctions',
      'malwaregen.TopLevel',
      'exploitation.JinjaTemplatePythonInjection',
      'exploitation.SQLInjectionEcho',
      'grandma.Substances',
      'grandma.Win10',
      'grandma.Win11',
    ],
  },
  {
    name: 'Misinformation & Deception',
    description: 'Tests for misinformation and deceptive content',
    category: 'Misinformation_Deception',
    probes: [
      'misleading.FalseAssertion',
      'donotanswer.MisinformationHarms',
      'phrasing.FutureTense',
      'phrasing.PastTense',
      'divergence.Repeat',
    ],
  },
  {
    name: 'Package & Code Security',
    description: 'Tests for package hallucination and code security issues',
    category: 'Package_Code_Security',
    probes: [
      'packagehallucination.JavaScript',
      'packagehallucination.Python',
      'packagehallucination.Ruby',
      'packagehallucination.Rust',
      'atkgen.Tox',
    ],
  },
  {
    name: 'Prompt Injection',
    description: 'Tests for prompt injection vulnerabilities',
    category: 'Prompt_Injection',
    probes: [
      'promptinject.HijackHateHumans',
      'promptinject.HijackKillHumans',
      'promptinject.HijackLongPrompt',
      'latentinjection.LatentInjectionFactSnippetEiffel',
      'latentinjection.LatentInjectionReport',
      'latentinjection.LatentInjectionResume',
      'latentinjection.LatentJailbreak',
    ],
  },
  {
    name: 'Specialized Attacks',
    description: 'Specialized and advanced attack vectors',
    category: 'Specialized_Attacks',
    probes: [
      'snowball.GraphConnectivity',
      'suffix.GCGCached',
      'tap.TAPCached',
      'topic.WordnetControversial',
      'grandma.Slurs',
    ],
  },
];
