import config from '@/config';
import { TenantPrismaClient } from '@/config/prisma';
import validator from '@/function/validator';
import { PrismaClient } from '../generated/index';
import {
  ApproveCompany,
  DeleteCompany,
  ListCompany,
  RejectCompany,
} from '@/types/model/company.model';
import { AppError } from '@/utils/customErrors';
import { executeWithMigration } from '@/utils/tenantDbOperation';
import {
  approveCompanyValidation,
  CompanyValidation,
  deleteCompanyValidation,
  listCompanyValidation,
  rejectCompanyValidation,
} from '@/validation/company.validation';
import bcrypt from 'bcryptjs';

export const validation: CompanyValidation = {
  approveCompany: validator(approveCompanyValidation),
  rejectCompany: validator(rejectCompanyValidation),
  deleteCompany: validator(deleteCompanyValidation),
  listCompany: validator(listCompanyValidation),
};

export const approveCompany: ApproveCompany = async params => {
  const prisma = new PrismaClient();

  const company = await prisma.company.findUnique({
    where: {
      id: params.id,
    },
  });
  if (!company) return AppError('Company not found', 404);

  // check if tenant schema are generated by company.tenantId
  const tenantId = company.tenantId;
  const tenantSchemaExists = await TenantPrismaClient.tenantSchemaExists(tenantId);
  if (tenantSchemaExists) return AppError('Tenant schema already exists', 400);

  await TenantPrismaClient.createTenantSchema(tenantId);

  // Use executeWithMigration for tenant operations
  const tenantUserResult = await executeWithMigration(
    tenantId,
    async () => {
      // connect to tenant schema
      const tenantPrisma = TenantPrismaClient.getClient(tenantId);
      await tenantPrisma.$connect();

      const hashedPassword = await bcrypt.hash('Company@123', config.BCRYPT_SALT_ROUNDS);

      // create tenant user
      return await tenantPrisma.user.create({
        data: {
          email: company.contactPersonEmail,
          password: hashedPassword,
          name: company.name, // Using company name as user name since contactPersonName doesn't exist
        },
      });
    },
    'create tenant user',
    ['user'] // Company approval needs user table for tenant user creation
  );

  // Check if tenant user creation failed
  if (
    tenantUserResult &&
    typeof tenantUserResult === 'object' &&
    'statusCode' in tenantUserResult
  ) {
    return tenantUserResult; // Return the error
  }

  // update company status
  return await prisma.company.update({
    where: {
      id: params.id,
    },
    data: {
      status: 'APPROVED',
      approvedAt: new Date(),
      dbCreated: true,
      dbCreatedAt: new Date(),
    },
  });
};

export const rejectCompany: RejectCompany = async params => {
  const prisma = new PrismaClient();
  const company = await prisma.company.findUnique({
    where: {
      id: params.id,
    },
  });
  if (!company) return AppError('Company not found', 404);

  return await prisma.company.update({
    where: {
      id: params.id,
    },
    data: {
      status: 'REJECTED',
      rejectedAt: new Date(),
      rejectionReason: params.reason,
    },
  });
};

// paginated list
export const listCompany: ListCompany = async params => {
  const { page, limit, search, field, sort, status, startDate, endDate, dateField, sortBy } =
    params;
  const where: Record<string, unknown> = {};
  if (field && search) {
    where[`${field}`] = {
      contains: search,
    };
  }
  if (status) {
    where.status = status;
  }
  if (startDate && endDate && dateField) {
    where[`${dateField}`] = {
      gte: new Date(startDate),
      lte: new Date(endDate),
    };
  }
  if (sortBy) {
    where[`${sortBy}`] = {
      sort,
    };
  }

  const prisma = new PrismaClient();
  // make pagination object for frontend - atomic transaction
  return await prisma.$transaction(async tx => {
    const totalDocs = await tx.company.count({
      where,
    });
    const totalPages = Math.ceil(totalDocs / limit);

    const docs = await tx.company.findMany({
      where,
      skip: (page - 1) * limit,
      take: limit,
    });
    const hasNextPage = page < totalPages;
    const hasPreviousPage = page > 1;
    const currentPage = page;
    const totalCount = totalDocs;

    return { docs, totalCount, totalPages, currentPage, hasNextPage, hasPreviousPage };
  });
};

export const deleteCompany: DeleteCompany = async params => {
  const prisma = new PrismaClient();

  try {
    // Check if company exists
    const company = await prisma.company.findUnique({
      where: { id: params.id },
    });

    if (!company) {
      return AppError('Company not found', 404);
    }

    // Check if company is approved (has tenantId) - only approved companies have tenant schemas
    const tenantId = company.tenantId;

    // Use transaction to ensure both operations succeed or fail together
    return await prisma.$transaction(async tx => {
      // If company has a tenant schema, delete it first
      if (tenantId) {
        try {
          await TenantPrismaClient.deleteTenantSchema(tenantId);
        } catch (error) {
          console.error(`Failed to delete tenant schema for company ${params.id}:`, error);
          throw new Error('Failed to delete tenant schema');
        }
      }

      // Delete the company record from public schema
      const deletedCompany = await tx.company.delete({
        where: { id: params.id },
      });

      // eslint-disable-next-line no-console
      console.log(`✅ Company deleted successfully: ${deletedCompany.name} (ID: ${params.id})`);
      return { message: 'Company deleted successfully' };
    });
  } catch (error) {
    console.error('Error deleting company:', error);
    return AppError('Failed to delete company', 500);
  }
};
